# Generated by Django 5.0.1 on 2024-02-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ideUser', models.IntegerField()),
                ('apenom', models.CharField(max_length=67)),
                ('claveUsuario', models.CharField(max_length=30)),
                ('clavePass', models.CharField(max_length=30)),
            ],
        ),
    ]
