# Generated by Django 5.0.1 on 2024-02-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facil', '0002_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='fotoArt',
            field=models.ImageField(default='NoDisponible.npg', upload_to='\\static\x07ssets\\img'),
        ),
    ]
