# Generated by Django 5.0.1 on 2024-02-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facil', '0003_articulo_fotoart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='fotoArt',
            field=models.ImageField(default='NoDisponible.png', upload_to='\\static\x07ssets\\img'),
        ),
    ]
