# Generated by Django 5.0.1 on 2024-02-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facil', '0004_alter_articulo_fotoart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contraseña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claveUsuario', models.CharField(max_length=30)),
                ('clavePass', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Galeria',
        ),
    ]
