# Generated by Django 5.0.1 on 2024-02-28 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facil', '0005_contraseña_delete_galeria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='fotoArt',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='precioArt',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='stockArt',
        ),
    ]
