# Generated by Django 5.0.1 on 2024-02-28 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facil', '0006_remove_articulo_fotoart_remove_articulo_precioart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='ideArt',
        ),
    ]
