# Generated by Django 5.0.1 on 2024-02-29 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facil', '0008_remove_usuario_ideuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='clavePass',
        ),
    ]
