# Generated by Django 5.0.1 on 2024-02-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facil', '0009_remove_usuario_clavepass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='apenom',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='claveUsuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
